<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Merge down and new</text>

        <Action name="LayerMergeDownAndNew">
        <icon></icon>
        <text>Merge down the current layer and create a new semitransparent layer</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>0</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>f</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>