<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Toggle dirty brush</text>

        <Action name="toggleDirtyBrush">
        <icon></icon>
        <text>Enable or disable the dirty brush</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>0</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut></shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>